### ISSUE TITLE
all reduce

### ISSUE THREAD

**Issue by anxuthu** [epfml/powersgd#10]
In the RankKReducer, the all reduce result is not divided by the number of workers. For example,

https://github.com/epfml/powersgd/blob/26f271a8671748542436685057c19cc0e0fde657/gradient_reducers.py#L753

Will this be an issue or am I missing something in the codes?

**Comment by tvogels** [comment]
Hi @anxuthu, thanks for the message.

This is a small performance optimization.

Later, in line  765

https://github.com/epfml/powersgd/blob/26f271a8671748542436685057c19cc0e0fde657/gradient_reducers.py#L765

the values for *p* are orthogonalized, so their magnitude is discarded. Dividing by *n* prior to orthogonalization would not influence the results.

Hope this helps. Feel free to reach out with other comments or questions.
