### ISSUE TITLE
Why svd_lowrank is faster than power iteration on CPU?

### ISSUE THREAD

**Issue by timmywanttolearn** [epfml/powersgd#13]
```
from powersgd import PowerSGD, Config, optimizer_step
import torch
import time
# params = torch.rand([64,32,112,112])
params = torch.rand([64,32,112,112])

# print(params)

powersgd = PowerSGD(params, config=Config(
    rank=1,  # lower rank => more aggressive compression
    min_compression_rate=1,  # don't compress gradients with less compression
    num_iters_per_step=2,  #   # lower number => more aggressive compression
    start_compressing_after_num_steps=0,
))
start = time.time()
powersgd._powersgd.aggregate(params)
end = time.time() -start
print(end)
start = time.time()
params = params.view(64,32,-1)
U,S,V = torch.svd_lowrank(params, q = 1)
end = time.time() -start
print(end)

```
you could see my code below.
Since your implementation produce P and Q matrixs. And svd_lowrank produce USV matirxs. U is the same shape as P and V is the same shape as Q.
The result is 
```
0.16216802597045898
0.046942949295043945
```

**Comment by tvogels** [comment]
Hi @timmywanttolearn ,

I can confirm that on my laptop, `torch.svd_lowrank` is faster than `powersgd._powersgd.aggregate` for your example
Have you also benchmarked it on a GPU? 

The P and Q from PowerSGD are not completely equivalent to the U and V of SVD, but indeed, both form a low-rank approximation.
SVD gives you the best possible low-rank approximation of the matrix of a single worker, but it cannot be used to directly make a low-rank approximation of the _average_ matrix between workers by integrating all-reduce averaging into the algorithm.

`torch.svd_lowrank` seems to be based on the following algorithm [(Halko et al. 2009)](https://arxiv.org/pdf/0909.4061.pdf), and computes the exact SVD of a random low-rank projection of the matrix:

<img width="1460" alt="image" src="https://user-images.githubusercontent.com/840825/168024913-044b45d0-31e4-4fbd-a7ef-82cf205e8948.png">

**Comment by timmywanttolearn** [comment]
> Maybe the reason why it is faster, is due to overhead in the PowerSGD implementation (grouping tensors, ...)
> 
> I ran the following example with a "minimal powersgd", where it is faster than `torch.svd_lowrank`.
> 
> ```
> from powersgd import PowerSGD, Config, optimizer_step
> import torch
> import time
> 
> param = torch.rand([1000, 1000])
> 
> powersgd = PowerSGD(
>     [param],
>     config=Config(
>         rank=1,  # lower rank => more aggressive compression
>         min_compression_rate=1,  # don't compress gradients with less compression
>         num_iters_per_step=2,  #   # lower number => more aggressive compression
>         start_compressing_after_num_steps=0,
>     ),
> )
> 
> # warmup
> for _ in range(10):
>     powersgd._powersgd.aggregate([param])
> 
> start = time.time()
> powersgd._powersgd.aggregate([param])
> print("PowerSGD        ", time.time() - start)
> 
> p = torch.randn([1000, 1])
> start = time.time()
> p /= p.norm()
> q = param @ p
> q /= q.norm()
> p = param.T @ q
> M = q @ p.T
> print("PowerSGD minimal ", time.time() - start)
> print("  Approximation error", torch.norm(M - param).item())
> 
> start = time.time()
> U, S, V = torch.svd_lowrank(param, q=1)
> M = U @ torch.diag(S) @ V.T
> print("SVD low rank    ", time.time() - start)
> print("  Approximation error", torch.norm(M - param).item())
> 
> start = time.time()
> U, S, V = torch.svd(param)
> M = U[:, :1] @ torch.diag(S[:1]) @ V[:, :1].T
> print("SVD             ", time.time() - start)
> print("  Approximation error", torch.norm(M - param).item())
> ```
> 
> Output:
> 
> ```
> ❯ python test.py
> PowerSGD         0.003081
> 
> PowerSGD minimal  0.000847
>   (Approximation error 285.2)
>   
> SVD low rank     0.001449
>   (Approximation error 285.1)
>   
> SVD              0.243178
>   (Approximation error 285.0)
> ```
> 
> It would be nice to know where all that time is going ..

oh, thank you very much. Seems if I change power iteration to a light form, then it will be faster. Have you ever implement it? If not, is it possible for me to write functions that change a matrix to P and Q matrix? 
And there is also one thing that I do not under stand, that why you write the code below?
https://github.com/epfml/powersgd/blob/master/powersgd/powersgd.py#:~:text=)%3A-,orthogonalize,-(in_batch)
I mean, in the paper, you claim that only P needs to be orthogonalized, but why do you even do orthogonalize to Q at odd number iteration?

**Comment by tvogels** [comment]
Regarding the orthogonalize, you are right. If you don't do too many iterations per SGD step, doing it only at the end is enough. 
The paper's code 
https://github.com/epfml/powersgd/blob/02d349f0b741e97f4338f17108c5afacf4dff274/paper-code/gradient_reducers.py#L741
only does it at the end.

The reason that this optimization is not in the code you are looking at is just for simplicity. Maybe it makes sense to add this optimization.

We'll try to identify what causes the overhead in the code, and bring the performance closer to the minimal example in performance.

**Comment by timmywanttolearn** [comment]
> f you don't do too many iterations per SGD step, doing it only at the end is enough.

Thank you very much!!!!!
I will do some work about this, if I have some findings I will connect you. And thank you and your team for powerSGD which is surely brilliant work!
