### ISSUE TITLE
Information on Timer Class

### ISSUE THREAD

**Issue by vineeths96** [epfml/powersgd#4]
I have a question regarding the implementation of the Timer class. In the line [here](https://github.com/epfml/powersgd/blob/3f4eb8d097e9a25ba4fd4b2ff1b2bf83c5aa665a/timer.py#L41), it is said that if the verbosity level is high the time is not measured. But in many places, like [here](https://github.com/epfml/powersgd/blob/3f4eb8d097e9a25ba4fd4b2ff1b2bf83c5aa665a/gradient_reducers.py#L57), the time is measured and displayed in the final output.

What am I missing here?

**Comment by tvogels** [comment]
Hello,

What's your setting for config["verbosity"]

**Comment by vineeths96** [comment]
The value of `config["log_verbosity"]` is 2. For some reason, I believed that `self.verbosity_level` was 1. It was a mistake on my end.
Thank you for the clarification.
