### ISSUE TITLE
TopKReducer class

### ISSUE THREAD

**Issue by vineeths96** [epfml/powersgd#5]
In the TopKReducer Class, at this line [here](https://github.com/epfml/powersgd/blob/3f4eb8d097e9a25ba4fd4b2ff1b2bf83c5aa665a/gradient_reducers.py#L231), we have, 
```
top_size = max(1, int(0.5 * self.rank * tensor.nelement()))
```

I believe that `self.rank` should be `self.compression`. If not can you explain the intuition behind this line?

**Comment by tvogels** [comment]
Hey! Thanks for reporting this. Indeed, this should be based on self.compression. I’ll fix it right away.

**Comment by vineeths96** [comment]
@tvogels Thanks for the update. I'm yet to go through the complete code. Once I'm done (within a day), I will be more than happy to create a PR.
