### ISSUE TITLE
Missing language_modeling.py?

### ISSUE THREAD

**Issue by bokunwang1** [epfml/powersgd#9]
It seems that there should be a “language_modeling.py” file in the “tasks” folder. But I can only see the “cifar.py”. Is it a missing file? Thanks.

**Comment by tvogels** [comment]
Hello, no this import statement should find https://github.com/epfml/powersgd/tree/master/tasks/language_modeling/__init__.py

Is the code not loading this correctly?

**Comment by bokunwang1** [comment]
Thanks.
